let express = require('express');
let router = express.Router();
let func = require('../config/function');
const userController = require('../controllers/user_controller');
router.post(func.urlCons.URL_USER_REGISTRATION, userController.userRegistration);
router.post(func.urlCons.URL_USER_LOGIN, userController.userLogin);
router.post(func.urlCons.URL_LINKED_LOGIN, userController.linkedInLogin);
router.get(func.urlCons.URL_USER_LIST, userController.getUserList);
router.post(func.urlCons.URL_TEMP_USER_DATA_SAVE, userController.tempUserRegister);
router.post(func.urlCons.URL_GET_TEMP_USER_DATA, userController.getTempUserData);
router.post(func.urlCons.URL_UPDATE_USER_REGISTRATION_STATUS, userController.updateUserRegisterStatus);
module.exports = router;